wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1669824926.614313
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.11
      5: 0.13.5
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 384
bbox_interval:
  desc: null
  value: -1
bbox_iou_optim:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: models/yolov5n.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: data/coco.yaml
data_dict:
  desc: null
  value:
    download: "from utils.general import download, Path\n\n\n# Download labels\nsegments\
      \ = False  # segment or box labels\ndir = Path(yaml['path'])  # dataset root\
      \ dir\nurl = 'https://github.com/ultralytics/yolov5/releases/download/v1.0/'\n\
      urls = [url + ('coco2017labels-segments.zip' if segments else 'coco2017labels.zip')]\
      \  # labels\ndownload(urls, dir=dir.parent)\n\n# Download data\nurls = ['http://images.cocodataset.org/zips/train2017.zip',\
      \  # 19G, 118k images\n        'http://images.cocodataset.org/zips/val2017.zip',\
      \  # 1G, 5k images\n        'http://images.cocodataset.org/zips/test2017.zip']\
      \  # 7G, 41k images (optional)\ndownload(urls, dir=dir / 'images', threads=3)\n"
    names:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
    nc: 80
    path: /data/detection_datasets/coco
    test: /data/detection_datasets/coco/test-dev2017.txt
    train: /data/detection_datasets/coco/train2017.txt
    val: /data/detection_datasets/coco/val2017.txt
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
multi_tensor_optimizer:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp50
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: ' '
workers:
  desc: null
  value: 8
