wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      BoundingBoxDebugger_wandb_delimeter_predictions:
        key: BoundingBoxDebugger_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': person
          '1': bicycle
          '10': fire hydrant
          '11': stop sign
          '12': parking meter
          '13': bench
          '14': bird
          '15': cat
          '16': dog
          '17': horse
          '18': sheep
          '19': cow
          '2': car
          '20': elephant
          '21': bear
          '22': zebra
          '23': giraffe
          '24': backpack
          '25': umbrella
          '26': handbag
          '27': tie
          '28': suitcase
          '29': frisbee
          '3': motorcycle
          '30': skis
          '31': snowboard
          '32': sports ball
          '33': kite
          '34': baseball bat
          '35': baseball glove
          '36': skateboard
          '37': surfboard
          '38': tennis racket
          '39': bottle
          '4': airplane
          '40': wine glass
          '41': cup
          '42': fork
          '43': knife
          '44': spoon
          '45': bowl
          '46': banana
          '47': apple
          '48': sandwich
          '49': orange
          '5': bus
          '50': broccoli
          '51': carrot
          '52': hot dog
          '53': pizza
          '54': donut
          '55': cake
          '56': chair
          '57': couch
          '58': potted plant
          '59': bed
          '6': train
          '60': dining table
          '61': toilet
          '62': tv
          '63': laptop
          '64': mouse
          '65': remote
          '66': keyboard
          '67': cell phone
          '68': microwave
          '69': oven
          '7': truck
          '70': toaster
          '71': sink
          '72': refrigerator
          '73': book
          '74': clock
          '75': vase
          '76': scissors
          '77': teddy bear
          '78': hair drier
          '79': toothbrush
          '8': boat
          '9': traffic light
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1669812508.185773
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.11
      5: 0.13.5
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bbox_iou_optim:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: models/yolov5s.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: data/coco128.yaml
data_dict:
  desc: null
  value:
    download: https://ultralytics.com/assets/coco128.zip
    names:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
    nc: 80
    path: /data/detection_datasets/coco128
    test: null
    train: /data/detection_datasets/coco128/images/train2017
    val: /data/detection_datasets/coco128/images/train2017
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
multi_tensor_optimizer:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp41
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: ' '
workers:
  desc: null
  value: 8
